from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Any
    import ast

def location_of(*args, **kwargs) -> 'Any': ...
def Call(*args, **kwargs) -> 'ast.Call': ...
def Name(*args, **kwargs) -> 'ast.Name': ...
def NameConstant(*args, **kwargs) -> 'ast.NameConstant': ...
def Str(*args, **kwargs) -> 'ast.Str': ...
