# -*- coding: utf-8 -*-
import sys
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Any
    import ast

def location_of(*args, **kwargs) -> 'Any': ...
def Call(*args, **kwargs) -> 'ast.Call': ...
def Name(*args, **kwargs) -> 'ast.Name': ...
def NameConstant(*args, **kwargs) -> 'ast.NameConstant': ...

if sys.version_info <= (3, 8):
    def Num(*args, **kwargs) -> 'ast.Num': ...
    def Str(*args, **kwargs) -> 'ast.Str': ...
else:
    def Num(*args, **kwargs) -> 'ast.Constant': ...
    def Str(*args, **kwargs) -> 'ast.Constant': ...
    def Constant(*args, **kwargs) -> 'ast.Constant': ...