# -*- coding: utf-8 -*-
from ipyflow.tracing.external_call_handler import (
    ListAppend,
    ListExtend,
    ListInsert,
    ListPop,
    ListRemove,
)

class list:
    def append(self, arg) -> ListAppend: ...
    def extend(self, args) -> ListExtend: ...
    def insert(self, pos, arg) -> ListInsert: ...
    def remove(self, arg) -> ListRemove: ...
    def pop(self, pos) -> ListPop: ...
