from ipyflow.annotations import Mutated, module, self

@module("sklearn.base")
class BaseEstimator:
    def fit(self) -> Mutated[self]: ...
    def fit_transform(self) -> Mutated[self]: ...

@module("sklearn.base")
class TransformerMixin:
    def fit(self) -> Mutated[self]: ...
    def fit_transform(self) -> Mutated[self]: ...

@module("sklearn.pipeline")
class Pipeline:
    def fit(self) -> Mutated[self]: ...
    def fit_transform(self) -> Mutated[self]: ...
