from ipyflow.annotations import Mutate, module, self

@module("sklearn.base")
class BaseEstimator:
    def fit(self) -> Mutate[self]: ...
    def fit_transform(self) -> Mutate[self]: ...

@module("sklearn.base")
class TransformerMixin:
    def fit(self) -> Mutate[self]: ...
    def fit_transform(self) -> Mutate[self]: ...

@module("sklearn.pipeline")
class Pipeline:
    def fit(self) -> Mutate[self]: ...
    def fit_transform(self) -> Mutate[self]: ...
